import React from 'react';
import './Terms.css'

const Terms = () => {
    return (
        <div className='terms'>
            <div className='terms__container'>
                <h1>Terms & Conditions</h1>
                <p className='update'>Last Updated: February 12, 2022</p>
                <p className='term__text'>BitBot Society is a collection of digital artworks (NFTs) running on the Ethereum network, This website is only an interface entirely responsible for the safety and management of their own private Ethereum wallets and validating all the transactions and contracts generated by this website before approval. Furthermore, as BitBot Society smart contract runs on the Ethernet network, there is no ability to undo, reverse, or restore any transactions. This website and its connected services are provided “ as is” and “as available” without warranty of any kind. By using this website you are accepting sole responsibility for any and all transactions involving BitBot Society digital collectibles.</p>
                <h3>These Terms & Conditions are subject to change.</h3>
                <p>These Terms may be discretionarily modified or replaced at any time, unless stated otherwise herein. The most current version of this Agreement will be posted on the Website with the “Last Revised” date at the top of the Agreement changed. Any changes or modifications will be effective immediately upon posting the revisions to the Site. You shall be responsible for reviewing and becoming familiar with any such modifications. You waive any right you may have to receive specific notice of such changes or modifications. Use of the Platform by you after any modification to the Agreement constitutes your acceptance of the Agreement as modified. If you do not agree to the Agreement in effect when you access or use the Platform, we may, at any time and without liability or prior notice, modify or discontinue all or part of the Platform (including access to the Platform via any third-party links).</p>
            </div>
        </div>
    );
}

export default Terms